# Generated by Django 3.2.4 on 2021-06-30 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_title', models.CharField(max_length=200)),
                ('experiment_description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('question_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Pairwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_algorithm', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(default='default/default.jpg', upload_to='choiceImages/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_algorithm', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(default='default/default.jpg', upload_to='choiceImages/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_algorithm', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(default='default/default.jpg', upload_to='choiceImages/')),
                ('select_choice', models.CharField(choices=[('INPUT_FIELD', 'Input field'), ('RADIO', 'Radio'), ('SLIDER', 'Slider')], max_length=50)),
                ('range_lower_bound', models.IntegerField(default=0)),
                ('range_upper_bound', models.IntegerField(default=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RatingGroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(default='default/default.jpg', upload_to='choiceImages/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RatingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('experimentRegister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentregister')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.rating')),
            ],
        ),
        migrations.CreateModel(
            name='RankingGroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(default='default/default.jpg', upload_to='choiceImages/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RankingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('experimentRegister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentregister')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.ranking')),
            ],
        ),
        migrations.CreateModel(
            name='PairwiseGroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(default='default/default.jpg', upload_to='choiceImages/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PairwiseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('experimentRegister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experimentregister')),
                ('pairwise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.pairwise')),
            ],
        ),
    ]
