# Generated by Django 3.2.4 on 2021-07-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentApp', '0005_alter_experiment_experiment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experiment')),
            ],
        ),
    ]
