# Generated by Django 3.2.4 on 2021-07-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentApp', '0006_experimentslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentCustomColours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_colour', models.CharField(max_length=7)),
                ('background_colour', models.CharField(max_length=7)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentApp.experiment')),
            ],
        ),
    ]
